1. Import the Numpy package under the name np

In [39]:
import numpy as np

2. Create a null vector of size 10

In [40]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a null vector of size 10 but the fifth value which is 1

In [41]:
np.put(null_vector, 4, 1)
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4. Create a vector with values ranging from 10 to 49

In [42]:
vec = np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


5. Reverse a vector (the first element becomes last)

In [43]:
print(vec[:: -1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [44]:
mat = np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Find indices of non­zero elements from [1,2,0,0,4,0]

In [45]:
a = [1, 2, 0, 0, 4, 0]
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

8. Create a 3x3x3 array with random values

In [46]:
arr3x3 = np.random.random((3,3,3))
print(arr3x3)

[[[0.1662611  0.49464531 0.03990744]
  [0.06418158 0.71918279 0.82694497]
  [0.93545476 0.18994902 0.03079968]]

 [[0.75517553 0.02133161 0.18752445]
  [0.3253046  0.57666525 0.95563894]
  [0.16796471 0.9737026  0.50982482]]

 [[0.49653193 0.85185205 0.14837813]
  [0.7638823  0.00670762 0.77472263]
  [0.48991434 0.11730014 0.90666004]]]


9. Create a random vector of size 30 and find the mean value

In [47]:
rand_vec = np.random.random(30)
print(rand_vec)

[0.07857914 0.14079372 0.84583696 0.33492121 0.03549195 0.99304685
 0.36725836 0.78736849 0.72528003 0.57190142 0.85975261 0.61679953
 0.67229685 0.45310597 0.02488029 0.26777032 0.97851237 0.26700215
 0.08345428 0.62254746 0.8855092  0.83337706 0.45671109 0.13393926
 0.85062517 0.82554323 0.26261388 0.83852144 0.91094422 0.88774114]


In [48]:
print("mean of rand_vec: ", np.mean(rand_vec))

mean of rand_vec:  0.5537375225752637


10. Create a 2d array with 1 on the border and 0 inside

In [49]:
twod_arr = np.full((3,3),1)
twod_arr[(1,1)] = 0
print(twod_arr)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


11. Create an 8x8 matrix and fill it with a checkerboard pattern

In [50]:
eight_arr = np.full((8,8),1)
eight_arr[1::2, ::2] = 0
eight_arr[0::2, 1::2] = 0
print( eight_arr)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


12. What is the major difference between sets, lists, tuples and dictionaries?

In [51]:
'''Ans: 
• Brackets : Sets{}, lists[], tuple(), dictionary{}
• Ordered - lists, tuple
  Unordered - sets, dictionary
• Allows duplicate - lists, tuple
  Don't - sets, dictionary
• Changeable - Sets, list, dictionary
  Not - Tuple'''

"Ans: \n• Brackets : Sets{}, lists[], tuple(), dictionary{}\n• Ordered - lists, tuple\n  Unordered - sets, dictionary\n• Allows duplicate - lists, tuple\n  Don't - sets, dictionary\n• Changeable - Sets, list, dictionary\n  Not - Tuple"

13. Print first 10 natural numbers using while loop

In [52]:
x = 0
while (x < 10):
    print(x)
    x += 1

0
1
2
3
4
5
6
7
8
9


14. Print the numbers -10 to -1 using for loop.

In [53]:
for i in range(-10,0,1):
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


15. Print the message “Done” after successful execution of any for a loop. 

In [54]:
x = 0
while (x <= 10):
    if x > 9:
        print("Done")
    else:
        print(x)
    x += 1

0
1
2
3
4
5
6
7
8
9
Done


16. Create a random vector of size 10 and sort it


In [55]:
rand = np.random.random(10)
np.sort(rand)

array([0.01605324, 0.11126162, 0.11857812, 0.1477211 , 0.51957239,
       0.54792137, 0.6583954 , 0.80986124, 0.8304694 , 0.94139751])

17. Execute any three math functions using NumPy.

In [56]:
#1st
np.min(rand)

0.016053235351272233

In [57]:
#2nd
np.max(rand)

0.9413975076174824

In [58]:
#3rd
np.median(rand)

0.5337468787796438